[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Mamadou Camara <mcamara@aneo.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
